inherit: ["config.yml"]
page_metric: A5
catalogfile: catalog.yml
# backcover: backcover.tex
bookname: book
texdocumentclass: ["review-jlreq", "media=ebook,paper=a5,fontsize=9pt,serial_pagination=true,tate,twoside,column_gap=2zw,onecolumn"]
# pdfmaker:
#   coverimage: c103frontcover.pdf