inherit: ["config.yml"]
stylesheet: vivliostyle-a5.css
# cover: null
coverimage: cover.png
titlepage: title.png
# titlefile: title.xhtml
colophon: true
backcover: backcover.png
# catalogfile: catalog.yml
bookname: book
booktitle: "並行現実小説集　総集編"
highlight:
  html: "rouge"