inherit: ["config.yml"]
bookname: louisa-complete-works-print
prt: ねこのしっぽ
texdocumentclass: ["review-jlreq", "media=print,paper=a5,fontsize=10pt,serial_pagination=true,hiddenfolio=shippo,startpage=3,tate,twoside,onecolumn,openany"]